### ISSUE TITLE
Current process remaining burst time equal to arriving process (SRTF)

### ISSUE THREAD

**Issue by manobendro** [vasu-gondaliya/cpu-scheduling-algorithms#1]
It chose arriving process when current process remaining brust time equal to arriving process (SRTF).

Tested example:

Process -> arriving time -> Burst time
p1 -> 6 -> 1
p2 -> 5 -> 2
p3 -> 4 -> 3
p4 -> 3 -> 4
p5 -> 2 -> 5
p6 -> 1 -> 6

**Comment by vasu-gondaliya** [comment]
I think you are saying that in this example when new process arrives, it starts running. But as the priority is given to process ID if same remaining burst time, as given as instructions, it is correct.

If still you feel any doubt, tell me.
