### ISSUE TITLE
Styling the input table

### ISSUE THREAD

**Issue by vasu-gondaliya** [vasu-gondaliya/cpu-scheduling-algorithms#3]
Add CSS to the input table for better experience.

**Comment by 96RadhikaJadhav** [comment]
@vasu-gondaliya Can I work on it?

**Comment by vasu-gondaliya** [comment]
Yes sure! Ask for help if you want.

**Comment by vasu-gondaliya** [comment]
Thank you @96RadhikaJadhav for working on this!
